### ISSUE TITLE
удалить гавно

### ISSUE THREAD

**Issue by ns3777k** [gromova-sn/firstNfast#2]
удалить .gitattributes и картинку

**Comment by ns3777k** [comment]
![kakoy-pacan_8617812_orig_](https://cloud.githubusercontent.com/assets/4613880/8757440/d7df2a3c-2ce2-11e5-962c-29423eb76128.jpg)

**Comment by gromova-sn** [comment]
https://github.com/gromova-sn/firstNfast/pull/3
